[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_movies_tokens = "zTaCpP3fLPMErJib4KLtfxMa5GT7YDmyxYZdddeCeDi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/kevin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
